//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobil
    {
        public int ID_Automobil { get; set; }
        public string Naziv { get; set; }
        public int Snaga { get; set; }
        public int Godina { get; set; }
        public string Gorivo { get; set; }
        public string Pogon { get; set; }
        public int Zapremnina { get; set; }
        public int ID_Proizvodac { get; set; }
        public int Cijena { get; set; }
    
        public virtual Proizvodac Proizvodac { get; set; }
    }
}
