//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvodac()
        {
            this.Automobils = new HashSet<Automobil>();
        }
    
        public int ID_Proizvodac { get; set; }
        public string Naziv { get; set; }
        public string Drzava { get; set; }
        public string Oznaka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Automobil> Automobils { get; set; }
    }
}
